/**
 * The Ontologizer Worker wrapper.
 *
 * Wraps the output generated by TeaVM so it can be used as a Worker.
 */

/* The TeaVM runtime refers to the global browser context sometimes */
window = self

/* We are using worker to access the worker */
worker = self

importScripts('worker/runtime.js', 'worker/classes.js');

console.log("Script Worker!");

main();
